# Generated by Django 5.2.6 on 2025-09-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_client_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "permissions": [
                    ("set_mailing_status", "Can disable mailing"),
                    ("view_mailing_list", "Can view mailing list"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
