# Generated by Django 5.2.6 on 2026-07-25 16:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_mailingattempt_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={},
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={},
        ),
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.RemoveField(
            model_name="client",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="clients",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="first_send_time",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="status",
        ),
        migrations.RemoveField(
            model_name="message",
            name="owner",
        ),
        migrations.AddField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(to="mailing.client"),
        ),
        migrations.AddField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 7, 25, 16, 17, 41, 350461, tzinfo=datetime.timezone.utc)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="full_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailing.message"),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="attempt_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="mailing.mailing"
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="server_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")], max_length=20),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(max_length=255),
        ),
    ]
