# Generated by Django 5.2.6 on 2026-07-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_client_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(related_name="mailings", to="mailing.client"),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")], max_length=50),
        ),
    ]
